version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.0.0 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run compile
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test-unit
      - run:
          name: deploy
          command: killall node && nohup npm run start 0<&- &>test.deploy.log &
      - run:
          name: check-deploy
          command: sleep 10s && cat test.deploy.log
      - run:
          name: deploy
          command: npm run test-api && killall node
      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_artifacts: # special step to save test results as as artifact
          path: lint-results.xml
          prefix: lints
      - store_test_results:
          path: test-results.xml
